contacts(notifications, breadcrumb) ::= <<
	$header()$
	$breadcrumbs(breadcrumb)$
	$alerts(notifications)$
	<div class="panel panel-default">
		<div class="panel-body">
	    	
			<div class="row">
	            <div class="col-lg-12">
	                <h2 class="page-header">Our Team</h2>
	            </div>
	            
	            <div class="col-lg-4 col-sm-6 text-center">
	                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
	                <h3>
	                	Brando Preda<br>
	                    <small>Software Developer</small>
	                </h3>
	                <a href="http://brandopreda.ninja" target="_blank" title="Personal site" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-link fa-stack-1x fa-inverse"></i>
					</a>
					<a href="https://www.linkedin.com/in/brandopreda" target="_blank" title="Linkedin account" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
					</a>
					<a href="https://github.com/brando91" target="_blank" title="Github account" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
					</a>
	            </div>
	            
	            <div class="col-lg-4 col-sm-6 text-center">
	                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
	                <h3>
	                	Riccardo Porrini<br>
	                    <small>PhD Student & Software Developer</small>
	                </h3>
	                <a href="http://rporrini.info/" target="_blank" title="Personal site" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-link fa-stack-1x fa-inverse"></i>
					</a>
					<a href="http://dblp.org/pid/56/8754" target="_blank" title="Publications" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-book fa-stack-1x fa-inverse"></i>
					</a>
					<a href="https://github.com/rporrini/" target="_blank" title="Github account" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
					</a>
	            </div>
	            
	            <div class="col-lg-4 col-sm-6 text-center">
	                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
	                <h3>
	                	Matteo Palmonari<br>
	                    <small>Assistant Professor</small>
	                </h3>
	                <a href="http://siti-server01.siti.disco.unimib.it/itislab/research/people/matteo-palmonari/" target="_blank" title="Personal site" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-link fa-stack-1x fa-inverse"></i>
					</a>
					<a href="http://dblp.org/pid/74/4142" target="_blank" title="Publications" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-book fa-stack-1x fa-inverse"></i>
					</a>
					<a href="https://www.researchgate.net/profile/Matteo_Palmonari" target="_blank" title="ResearchGate account" class="fa-stack fa-lg">
					  <i class="fa fa-circle fa-stack-2x"></i>
					  <i class="fa fa-university fa-stack-1x fa-inverse"></i>
					</a>
	            </div>
            </div>
			
	  	</div>
	</div>
	$footer()$
>>