header() ::= <<

	<!DOCTYPE html>
	<html lang="en">
  		<head>
		    <meta charset="utf-8">
		    <meta name="description" content="">
		    <meta name="author" content="">
		    <title>STAN</title>
		    <meta name="description" content="STAN is an online tool that lets you annotate your tables with semantics from popular ontologies and knowledge bases.">
			<link rel="shortcut icon" href="assets/img/favicon.ico" type="image/x-icon">
			
		    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
		    <link href="/assets/css/jquery-ui.min.css" rel="stylesheet">
		    <link href="/assets/css/jasny-bootstrap.min.css" rel="stylesheet">
		    <link href="/assets/css/style.css" rel="stylesheet">
		    <link href="/assets/css/bootstrap-table.css" rel="stylesheet">
		    
		    <script src="/assets/js/jquery-1.11.3.min.js"></script>
		    <script src="/assets/js/jquery-ui.min.js"></script>
		    <script src="/assets/js/bootstrap.min.js"></script>
		    <script src="/assets/js/jasny-bootstrap.min.js"></script>
		    <script src="/assets/js/bootstrap-table.js"></script>
		    <script src="/assets/js/stan.js"></script>
		    <script src="/assets/js/autocomplete.js"></script>
		</head>
	
	  <body>
	
	    <div class="container">
	    	<div class="page-header">
		  		<h1><small class="pull-right sub-title">Semantic Table Annotation Tool</small></h1>
		  		<a href="/"><img src="/assets/img/STAN.png"></a>
			</div>

>>